### PR TITLE
Added new_code_block to MarkdownGenerator

### PR DESCRIPTION
**Pull request by shngt**
Added new method for markdown formatting for code blocks. Addresses issue #5

### CODE REVIEW

**Comment by shngt** [comment]
Would it be helpful if I rebased on dev?

**Comment by IgnisDa** [comment]
Looks like there are a few merge conflicts. Rebasing would be a good idea. The code looks good, so well done!

**Comment by shngt** [comment]
Did the rebase, but tests are not passing due to some changes in new_ordered_list in dev

**Comment by IgnisDa** [comment]
Yeah the tests are failing because of some errors in source code, I have no idea how to fix them. I'll comment out the tests in your commit and then merge them.

**Comment by IgnisDa** [comment]
Awesome work! Please add your name to `contributors.md`. I will merge your PR tomorrow.

**Comment by shngt** [comment]
Thank you! :) will do

**Comment by IgnisDa** [comment]
I also commented out the failing tests so your next commit's build will be successful (just make sure you merge this branch into yours first).

**Comment by shngt** [comment]
@IgnisDa thank you! Repushed

**Comment by IgnisDa** [comment]
Thanks again for contributing!

**Pull request merged**
